# Automatically generated by Pynguin.
import rabbitmq as module_0


def test_case_0():
    try:
        int_0 = -285
        pika_queue_0 = module_0.PikaQueue(int_0)
    except BaseException:
        pass


def test_case_1():
    try:
        list_0 = None
        amqp_queue_0 = module_0.AmqpQueue(list_0)
    except BaseException:
        pass


def test_case_2():
    try:
        str_0 = '8*]Ox'
        amqp_queue_0 = module_0.AmqpQueue(str_0, str_0)
    except BaseException:
        pass


def test_case_3():
    try:
        float_0 = None
        set_0 = {float_0}
        complex_0 = None
        int_0 = -2013
        pika_queue_0 = module_0.PikaQueue(set_0, complex_0, int_0)
    except BaseException:
        pass


def test_case_4():
    try:
        int_0 = None
        bytes_0 = b',g\xaa\xc0m\x7f\xef\x9a\\m\xc8\xa9\x8d\xad\xc3\xa3n\xd3'
        set_0 = set()
        pika_queue_0 = module_0.PikaQueue(int_0, bytes_0, set_0, int_0)
    except BaseException:
        pass


def test_case_5():
    try:
        str_0 = ''
        amqp_queue_0 = module_0.AmqpQueue(str_0, str_0)
    except BaseException:
        pass


def test_case_6():
    try:
        str_0 = '=L{'
        amqp_queue_0 = module_0.AmqpQueue(str_0, str_0, str_0)
    except BaseException:
        pass


def test_case_7():
    try:
        str_0 = ''
        amqp_queue_0 = module_0.AmqpQueue(str_0, str_0, str_0, str_0)
    except BaseException:
        pass
