# Automatically generated by Pynguin.
import pytest
import redis_queue as module_0


def test_case_0():
    str_0 = 'yU;\x0b)b'
    redis_queue_0 = module_0.RedisQueue(str_0, str_0, str_0)
    assert redis_queue_0.name == 'yU;\x0b)b'
    assert redis_queue_0.maxsize == 0
    assert redis_queue_0.lazy_limit is True
    assert redis_queue_0.last_qsize == 0
    assert module_0.RedisQueue.max_timeout == pytest.approx(0.3, abs=0.01,
        rel=0.01)
