name: "chinese-match"

on:
  push:
  pull_request:
  schedule:
    - cron: '15 12 * * *'

jobs:
  chinese-match:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Grep Chinese
      run: cd ${{ github.workspace }}
    - run: echo ::set-output name=things::$(grep -rP --exclude-dir={node_modules,lib,dist,i18n} '[\p{Han}]' . | grep -v "Binary")
      id: grep_things
      shell: bash
    - run: echo "There's chinese in code!" 
      if:  steps.grep_things.outputs.things != ''
    - run: echo -e "${{ steps.grep_things.outputs.things }}"
      if:  steps.grep_things.outputs.things != ''
    - run: ddddd
      if:  steps.grep_things.outputs.things != ''
